### ISSUE TITLE
Service configuration

### ISSUE THREAD

**Issue by gonzaloetjo** [Lumyos/devops-labs#6]
API pod connection to MYSQL on the host.

**Comment by Lumyos** [comment]
I finally understand why it doesn't work.
Reminder of the problem: communication between two pods: mysql and nextjs-api: exec in an api container: communication with mysql works. but when SSH tunnels and connects outside the cluster, we can't add or display products.
Why: requests to the api are made client-side to localhost:3000 (url written in code). However, the client url changes, and is generated by minikube. 
Solution: I don't have a solution. I need to find a dynamic way to retrieve the url (in code) and thus adapt the request to the api.

**Comment by Lumyos** [comment]
problem solved.
